### PR TITLE
Fix renter spending reporting and current period

### LINKED ISSUE #3077: Change allowance mechanics to always extend by `period` time.
Currently, when your contracts renew, they renew so that there is `period` time left. This can create some confusing spending mechanics, where the first time you create contracts, you pay for 3 months of storage, but each time you renew after that you pay for 6 weeks of storage. It also means that up to your full allowance gets spent every 6 weeks, and users might be expecting that allowance to cover 3 months of storage, because indeed it does cover 3 months of storage for the first iteration only.

We can clear up a lot of this confusion just by making the allowance extend by the full period instead of extending up to the full period of time remaining.

### PR DESCRIPTION
**Pull request by MSevey**
Updated `PeriodSpending` for renter spending with siatest

updated renter's `CurrentPeriod` and added siatest

The only time that I can think of that the spending might still not be reported accurately is during the maturity delay window, when the unspent allocated funds have not be released to the renter.

This resolves #3077

### CODE REVIEW

**Comment by MSevey** [comment]
This should also resolve #2308  @DavidVorick please confirm

File: modules/renter/contractor/contractor_test.go [hunk 1]
```diff
@@ -116,69 +114,6 @@ func (stubHostDB) ScoreBreakdown(modules.HostDBEntry) modules.HostScoreBreakdown
 	return modules.HostScoreBreakdown{}
 }
 
-// TestAllowancePeriodTracking verifies that the contractor tracks its current
-// period correctly as renewals occur.
-func TestAllowancePeriodTracking(t *testing.T) {
```
Comment (MSevey) [inline modules/renter/contractor/contractor_test.go]: My siatests cover this now

File: modules/renter/contractor/contracts.go [hunk 2]
```diff
@@ -416,16 +417,37 @@ func (c *Contractor) threadedContractMaintenance() {
...
-			renewAmount := contract.TotalCost.Sub(contract.ContractFee).Sub(contract.TxnFee).Sub(contract.SiafundFee).Sub(contract.RenterFunds)
+			//
+			// In order to accurately fund contracts based on variable spending,
+			// the cost per block is calculated based on the total spent
+			// over the length of time that the contract was active before
+			// renewal.
+			oldContractSpent := contract.TotalCost.Sub(contract.ContractFee).Sub(contract.TxnFee).Sub(contract.SiafundFee).Sub(contract.RenterFunds)
+			oldContractLength := blockHeight - contract.StartHeight
+			if oldContractLength <= 1 {
+				oldContractLength = types.BlockHeight(1)
```
Comment (lukechampine) [inline modules/renter/contractor/contracts.go]: since these are unsigned ints, `== 0` is probably clearer, and makes it more obvious that we're trying to avoid a divide-by-zero panic.

File: cmd/siac/main.go [hunk 3]
```diff
@@ -124,6 +125,7 @@ func main() {
 	renterAllowanceCmd.AddCommand(renterAllowanceCancelCmd)
 
 	renterCmd.Flags().BoolVarP(&renterListVerbose, "verbose", "v", false, "Show additional file info such as redundancy")
+	renterContractsCmd.Flags().BoolVarP(&renterAllContracts, "all", "A", false, "Show all expired contracts in addition to active contracts")
```
Comment (DavidVorick) [inline cmd/siac/main.go]: is there a reason that we use captial A and capital H as the flags instead of the lowercase alternatives?

File: cmd/siac/export.go [hunk 4]
```diff
@@ -35,7 +35,8 @@ func renterexportcontracttxnscmd(destination string) {
 		die("Could not retrieve contracts:", err)
 	}
 	var contractTxns []types.Transaction
-	for _, c := range cs.Contracts {
+	contracts := append(cs.Contracts, cs.OldContracts...)
+	for _, c := range contracts {
```
[the remark this answers is not in the document]
Comment (MSevey) [reply cmd/siac/export.go]: if you're worried about breaking compatibility I can remove that and we can discuss what to do with a separate PR

File: cmd/siac/main.go (hunk 3 above)
Comment (MSevey) [reply cmd/siac/main.go]: lower case a is a global flag i think so I did capital A to avoid any potential conflicts. If we prefer lower case letters I can do `old` and `o` instead.

File: modules/renter/contractor/contractor.go [hunk 5]
```diff
@@ -108,8 +110,23 @@ func (c *Contractor) PeriodSpending() modules.ContractorSpending {
 			spending.DownloadSpending = spending.DownloadSpending.Add(old.DownloadSpending)
 			spending.UploadSpending = spending.UploadSpending.Add(old.UploadSpending)
 			spending.StorageSpending = spending.StorageSpending.Add(old.StorageSpending)
+		} else if exist && old.EndHeight+host.WindowSize+types.MaturityDelay > c.blockHeight {
+			// Calculate funds that are being withheld in contracts
+			spending.WithheldFunds = spending.WithheldFunds.Add(old.RenterFunds)
+			// Record the largest window size for worst case when reporting the spending
+			if host.WindowSize >= spending.ReleaseBlock {
```
Comment (DavidVorick) [inline modules/renter/contractor/contractor.go]: Should this be old.EndHeight + host.WindowSize + types.MaturityDelay?
